"""
Name Manager comments on defined names: storage, limits, round-trip.

tests/test_name_mgr_comments.py

The name_mgr_comment field (2026-08-17) writes Excel's Name Manager
Comment column - the comment attribute on the definedName element in
xl/workbook.xml. One funnel serves every producer: create_from_columns
range specs, YAML library objects on import, and copy_direct. Exports
harvest stored comments back into the YAML so a hand-entered comment is
never the one property that export silently drops.

Excel's dialog caps the field at 255 characters and truncates silently;
the funnel refuses over-length text loudly instead, and flattens
multi-line YAML to the single line the dialog renders.

Runnable with pytest, but written to run standalone and report a score.
Exercises real workbooks on disk rather than mocks, because the whole
point is what Excel ends up seeing.
"""

import sys
import openpyxl
import tempfile

from pathlib import Path

from excel_recipe_processor.core.base_processor import StepProcessorError
from excel_recipe_processor.processors.manage_named_objects_processor import (
    ManageNamedObjectsProcessor
)


def build_lookup_workbook(path: str) -> None:
    """Build a small workbook with one lookup-shaped sheet."""
    workbook = openpyxl.Workbook()
    worksheet = workbook.active
    worksheet.title = 'Decode'

    worksheet.append(['Indicator', 'Relevant Date'])
    for row_num in range(1, 6):
        worksheet.append([f'Indicator {row_num}', f'Date field {row_num}'])

    workbook.save(path)
    workbook.close()


def make_export_processor(temp_dir: str):
    """Processor armed for export_all against a throwaway target."""
    return ManageNamedObjectsProcessor({
        'processor_type': 'manage_named_objects',
        'operation': 'export_all',
        'source_file': str(Path(temp_dir) / 'source.xlsx'),
        'yaml_file': str(Path(temp_dir) / 'export.yaml'),
    })


def test_create_from_columns_stores_comment():
    """A range spec's name_mgr_comment lands in the stored workbook."""
    print("Testing create_from_columns comment storage...")

    with tempfile.TemporaryDirectory() as temp_dir:
        target = str(Path(temp_dir) / 'lookup.xlsx')
        build_lookup_workbook(target)

        comment_text = 'Indicator decode key. Regenerated by recipe on every run.'
        processor = ManageNamedObjectsProcessor({
            'processor_type': 'manage_named_objects',
            'operation': 'create_from_columns',
            'target_file': target,
            'ranges': [
                {'name': 'rng_indicator', 'sheet_name': 'Decode',
                 'columns': ['Indicator'], 'row_mode': 'data',
                 'name_mgr_comment': comment_text},
                {'name': 'rng_no_comment', 'sheet_name': 'Decode',
                 'columns': ['Relevant Date'], 'row_mode': 'data'},
            ]
        })
        processor.execute()

        workbook = openpyxl.load_workbook(target)
        with_comment = workbook.defined_names['rng_indicator'].comment
        without = workbook.defined_names['rng_no_comment'].comment
        workbook.close()

    passed = True
    if with_comment == comment_text:
        print(f"  ✓ comment stored and reloaded: {with_comment!r}")
    else:
        print(f"  ✗ expected {comment_text!r}, stored {with_comment!r}")
        passed = False

    if without is None:
        print("  ✓ omitted name_mgr_comment stores no comment")
    else:
        print(f"  ✗ comment-free range grew a comment: {without!r}")
        passed = False

    return passed


def test_multiline_yaml_text_is_flattened():
    """Folded YAML newlines collapse to the single line the dialog renders."""
    print("\nTesting whitespace flattening...")

    with tempfile.TemporaryDirectory() as temp_dir:
        target = str(Path(temp_dir) / 'lookup.xlsx')
        build_lookup_workbook(target)

        processor = ManageNamedObjectsProcessor({
            'processor_type': 'manage_named_objects',
            'operation': 'create_from_columns',
            'target_file': target,
            'ranges': [
                {'name': 'rng_indicator', 'sheet_name': 'Decode',
                 'columns': ['Indicator'], 'row_mode': 'data',
                 'name_mgr_comment': 'Line one\ncontinues here\n  with   runs'},
            ]
        })
        processor.execute()

        workbook = openpyxl.load_workbook(target)
        stored = workbook.defined_names['rng_indicator'].comment
        workbook.close()

    expected = 'Line one continues here with runs'
    if stored == expected:
        print(f"  ✓ flattened to one line: {stored!r}")
        return True
    print(f"  ✗ expected {expected!r}, stored {stored!r}")
    return False


def test_over_limit_refused_with_guidance():
    """Text past 255 chars fails loud, naming the limit and the fix."""
    print("\nTesting the 255-character ceiling...")

    with tempfile.TemporaryDirectory() as temp_dir:
        target = str(Path(temp_dir) / 'lookup.xlsx')
        build_lookup_workbook(target)

        processor = ManageNamedObjectsProcessor({
            'processor_type': 'manage_named_objects',
            'operation': 'create_from_columns',
            'target_file': target,
            'ranges': [
                {'name': 'rng_indicator', 'sheet_name': 'Decode',
                 'columns': ['Indicator'], 'row_mode': 'data',
                 'name_mgr_comment': 'x' * 300},
            ]
        })

        try:
            processor.execute()
        except StepProcessorError as error:
            message = str(error)
            wanted = ['255', 'name_mgr_comment', 'rng_indicator', 'description']
            missing = [term for term in wanted if term not in message]
            if not missing:
                print("  ✓ refused loudly; guidance names limit, field and fix")
                return True
            print(f"  ✗ guidance missing {missing}: {message[:140]}")
            return False

    print("  ✗ over-length comment was accepted")
    return False


def test_wrong_key_gets_guided_error():
    """'comment' in a range spec is caught and taught, not ignored."""
    print("\nTesting wrong-key guidance...")

    with tempfile.TemporaryDirectory() as temp_dir:
        target = str(Path(temp_dir) / 'lookup.xlsx')
        build_lookup_workbook(target)

        processor = ManageNamedObjectsProcessor({
            'processor_type': 'manage_named_objects',
            'operation': 'create_from_columns',
            'target_file': target,
            'ranges': [
                {'name': 'rng_indicator', 'sheet_name': 'Decode',
                 'columns': ['Indicator'], 'row_mode': 'data',
                 'comment': 'lands nowhere without guidance'},
            ]
        })

        try:
            processor.execute()
        except StepProcessorError as error:
            if 'name_mgr_comment' in str(error):
                print("  ✓ wrong key refused; error names name_mgr_comment")
                return True
            print(f"  ✗ error lacks the correct key name: {error}")
            return False

    print("  ✗ 'comment' key was silently ignored")
    return False


def test_export_import_round_trip():
    """A stored comment survives export to YAML and import to a new file."""
    print("\nTesting export/import round-trip...")

    comment_text = 'Hand-entered in Excel; must survive the harvest cycle.'

    with tempfile.TemporaryDirectory() as temp_dir:
        source = str(Path(temp_dir) / 'source.xlsx')
        target = str(Path(temp_dir) / 'target.xlsx')
        yaml_file = str(Path(temp_dir) / 'export.yaml')

        build_lookup_workbook(source)
        workbook = openpyxl.load_workbook(source)
        from openpyxl.workbook.defined_name import DefinedName
        workbook.defined_names['rng_indicator'] = DefinedName(
            'rng_indicator', attr_text='Decode!$A$2:$A$6', comment=comment_text
        )
        workbook.save(source)
        workbook.close()

        build_lookup_workbook(target)

        exporter = ManageNamedObjectsProcessor({
            'processor_type': 'manage_named_objects',
            'operation': 'export_all',
            'source_file': source,
            'yaml_file': yaml_file,
        })
        export_result = exporter.execute()

        importer = ManageNamedObjectsProcessor({
            'processor_type': 'manage_named_objects',
            'operation': 'import_all',
            'yaml_file': yaml_file,
            'target_file': target,
            'on_existing': 'replace',
        })
        importer.execute()

        workbook = openpyxl.load_workbook(target)
        landed = workbook.defined_names['rng_indicator'].comment
        workbook.close()

    if landed == comment_text:
        print(f"  ✓ comment survived workbook -> YAML -> workbook: {landed!r}")
        return True
    print(f"  ✗ expected {comment_text!r}, landed {landed!r}")
    return False


def main():
    """Run every test and report a final score."""
    print("=== Name Manager comment tests ===")

    tests = [
        test_create_from_columns_stores_comment,
        test_multiline_yaml_text_is_flattened,
        test_over_limit_refused_with_guidance,
        test_wrong_key_gets_guided_error,
        test_export_import_round_trip,
    ]

    passed = 0
    for test_func in tests:
        try:
            if test_func():
                passed += 1
        except Exception as error:
            print(f"✗ {test_func.__name__} crashed: {error}")

    print(f"\n=== Results: {passed}/{len(tests)} tests passed ===")
    return passed == len(tests)


if __name__ == '__main__':
    sys.exit(0 if main() else 1)

# End of file #
